import io
from ..compat import compat_etree_fromstring as compat_etree_fromstring
from ..networking.exceptions import HTTPError as HTTPError
from ..utils import fix_xml_ampersands as fix_xml_ampersands, xpath_text as xpath_text
from .fragment import FragmentFD as FragmentFD

class DataTruncatedError(Exception): ...

class FlvReader(io.BytesIO):
    def read_bytes(self, n): ...
    def read_unsigned_long_long(self): ...
    def read_unsigned_int(self): ...
    def read_unsigned_char(self): ...
    def read_string(self): ...
    def read_box_info(self): ...
    def read_asrt(self): ...
    def read_afrt(self): ...
    def read_abst(self): ...
    def read_bootstrap_info(self): ...

def read_bootstrap_info(bootstrap_bytes): ...
def build_fragments_list(boot_info): ...
def write_unsigned_int(stream, val) -> None: ...
def write_unsigned_int_24(stream, val) -> None: ...
def write_flv_header(stream) -> None: ...
def write_metadata_tag(stream, metadata) -> None: ...
def remove_encrypted_media(media): ...
def get_base_url(manifest): ...

class F4mFD(FragmentFD):
    def real_download(self, filename, info_dict): ...
