import xml.etree.ElementTree as etree
from .compat_utils import passthrough_module as passthrough_module
from _typeshed import Incomplete

class compat_HTMLParseError(ValueError): ...

class _TreeBuilder(etree.TreeBuilder):
    def doctype(self, name, pubid, system) -> None: ...

def compat_etree_fromstring(text): ...
def compat_ord(c): ...
def compat_expanduser(path): ...

compat_expanduser: Incomplete

def urllib_req_to_req(urllib_request): ...
