from _typeshed import Incomplete
from collections.abc import Generator

def gen_extractor_classes(): ...
def gen_extractors(): ...
def list_extractor_classes(age_limit=None) -> Generator[Incomplete, Incomplete, Incomplete]: ...
def list_extractors(age_limit=None): ...
def get_info_extractor(ie_name): ...
def import_extractors() -> None: ...
