from ..utils import ExtractorError as ExtractorError, OnDemandPagedList as OnDemandPagedList, int_or_none as int_or_none, join_nonempty as join_nonempty, parse_qs as parse_qs, urljoin as urljoin
from ..utils.traversal import traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class AllstarBaseIE(InfoExtractor): ...
class AllstarIE(AllstarBaseIE): ...
class AllstarProfileIE(AllstarBaseIE): ...
