from ..utils import clean_html as clean_html, dict_get as dict_get, get_element_by_class as get_element_by_class, int_or_none as int_or_none, unified_strdate as unified_strdate, url_or_none as url_or_none
from .common import InfoExtractor as InfoExtractor

class Alsace20TVBaseIE(InfoExtractor): ...
class Alsace20TVIE(Alsace20TVBaseIE): ...
class Alsace20TVEmbedIE(Alsace20TVBaseIE): ...
