from ..utils import ExtractorError as ExtractorError, GeoRestrictedError as GeoRestrictedError, int_or_none as int_or_none, join_nonempty as join_nonempty, parse_iso8601 as parse_iso8601, parse_qs as parse_qs, strip_or_none as strip_or_none, traverse_obj as traverse_obj, url_or_none as url_or_none
from .common import InfoExtractor as InfoExtractor

class ArteTVBaseIE(InfoExtractor): ...
class ArteTVIE(ArteTVBaseIE): ...
class ArteTVEmbedIE(InfoExtractor): ...
class ArteTVPlaylistIE(ArteTVBaseIE): ...

class ArteTVCategoryIE(ArteTVBaseIE):
    @classmethod
    def suitable(cls, url): ...
