from .common import InfoExtractor as InfoExtractor
from .youtube import YoutubeIE as YoutubeIE, YoutubeTabIE as YoutubeTabIE

class BeatBumpVideoIE(InfoExtractor): ...
class BeatBumpPlaylistIE(InfoExtractor): ...
