from ..dependencies import Cryptodome as Cryptodome
from ..networking.exceptions import HTTPError as HTTPError
from ..utils import ExtractorError as ExtractorError, GeoRestrictedError as GeoRestrictedError, InAdvancePagedList as InAdvancePagedList, OnDemandPagedList as OnDemandPagedList, bool_or_none as bool_or_none, determine_ext as determine_ext, filter_dict as filter_dict, float_or_none as float_or_none, format_field as format_field, get_element_by_class as get_element_by_class, int_or_none as int_or_none, join_nonempty as join_nonempty, make_archive_id as make_archive_id, merge_dicts as merge_dicts, mimetype2ext as mimetype2ext, parse_count as parse_count, parse_qs as parse_qs, parse_resolution as parse_resolution, qualities as qualities, smuggle_url as smuggle_url, srt_subtitles_timecode as srt_subtitles_timecode, str_or_none as str_or_none, traverse_obj as traverse_obj, unified_timestamp as unified_timestamp, unsmuggle_url as unsmuggle_url, url_or_none as url_or_none, urlencode_postdata as urlencode_postdata, variadic as variadic
from .common import InfoExtractor as InfoExtractor, SearchInfoExtractor as SearchInfoExtractor

class BilibiliBaseIE(InfoExtractor):
    @property
    def is_logged_in(self): ...
    def extract_formats(self, play_info): ...
    def json2srt(self, json_data): ...

class BiliBiliIE(BilibiliBaseIE): ...
class BiliBiliBangumiIE(BilibiliBaseIE): ...
class BiliBiliBangumiMediaIE(BilibiliBaseIE): ...
class BiliBiliBangumiSeasonIE(BilibiliBaseIE): ...
class BilibiliCheeseBaseIE(BilibiliBaseIE): ...
class BilibiliCheeseIE(BilibiliCheeseBaseIE): ...
class BilibiliCheeseSeasonIE(BilibiliCheeseBaseIE): ...
class BilibiliSpaceBaseIE(BilibiliBaseIE): ...
class BilibiliSpaceVideoIE(BilibiliSpaceBaseIE): ...
class BilibiliSpaceAudioIE(BilibiliSpaceBaseIE): ...
class BilibiliSpaceListBaseIE(BilibiliSpaceBaseIE): ...

class BilibiliCollectionListIE(BilibiliSpaceListBaseIE):
    @classmethod
    def suitable(cls, url): ...

class BilibiliSeriesListIE(BilibiliSpaceListBaseIE): ...
class BilibiliFavoritesListIE(BilibiliSpaceListBaseIE): ...
class BilibiliWatchlaterIE(BilibiliSpaceListBaseIE): ...
class BilibiliPlaylistIE(BilibiliSpaceListBaseIE): ...

class BilibiliCategoryIE(InfoExtractor):
    IE_NAME: str

class BiliBiliSearchIE(SearchInfoExtractor):
    IE_DESC: str

class BilibiliAudioBaseIE(InfoExtractor): ...
class BilibiliAudioIE(BilibiliAudioBaseIE): ...
class BilibiliAudioAlbumIE(BilibiliAudioBaseIE): ...
class BiliBiliPlayerIE(InfoExtractor): ...
class BiliBiliDynamicIE(InfoExtractor): ...

class BiliIntlBaseIE(InfoExtractor):
    def json2srt(self, json): ...

class BiliIntlIE(BiliIntlBaseIE): ...

class BiliIntlSeriesIE(BiliIntlBaseIE):
    IE_NAME: str

class BiliLiveIE(InfoExtractor): ...
