from ..utils import clean_html as clean_html, parse_duration as parse_duration, str_to_int as str_to_int, unified_strdate as unified_strdate
from .common import InfoExtractor as InfoExtractor

class CamdemyIE(InfoExtractor): ...
class CamdemyFolderIE(InfoExtractor): ...
