from ..networking.exceptions import HTTPError as HTTPError
from ..utils import ExtractorError as ExtractorError, determine_ext as determine_ext, float_or_none as float_or_none, int_or_none as int_or_none, remove_start as remove_start, strip_or_none as strip_or_none, try_get as try_get, unified_timestamp as unified_timestamp
from .common import InfoExtractor as InfoExtractor

class DPlayBaseIE(InfoExtractor): ...
class DPlayIE(DPlayBaseIE): ...
class DiscoveryPlusBaseIE(DPlayBaseIE): ...
class HGTVDeIE(DiscoveryPlusBaseIE): ...
class GoDiscoveryIE(DiscoveryPlusBaseIE): ...
class TravelChannelIE(DiscoveryPlusBaseIE): ...
class CookingChannelIE(DiscoveryPlusBaseIE): ...
class HGTVUsaIE(DiscoveryPlusBaseIE): ...
class FoodNetworkIE(DiscoveryPlusBaseIE): ...
class DestinationAmericaIE(DiscoveryPlusBaseIE): ...
class InvestigationDiscoveryIE(DiscoveryPlusBaseIE): ...
class AmHistoryChannelIE(DiscoveryPlusBaseIE): ...
class ScienceChannelIE(DiscoveryPlusBaseIE): ...
class DiscoveryLifeIE(DiscoveryPlusBaseIE): ...
class AnimalPlanetIE(DiscoveryPlusBaseIE): ...
class TLCIE(DiscoveryPlusBaseIE): ...
class DiscoveryPlusIE(DiscoveryPlusBaseIE): ...
class DiscoveryPlusIndiaIE(DiscoveryPlusBaseIE): ...
class DiscoveryNetworksDeIE(DiscoveryPlusBaseIE): ...
class DiscoveryPlusShowBaseIE(DPlayBaseIE): ...
class DiscoveryPlusItalyIE(DiscoveryPlusBaseIE): ...
class DiscoveryPlusItalyShowIE(DiscoveryPlusShowBaseIE): ...
class DiscoveryPlusIndiaShowIE(DiscoveryPlusShowBaseIE): ...
