from ..utils import determine_ext as determine_ext, dict_get as dict_get, int_or_none as int_or_none, traverse_obj as traverse_obj, unified_strdate as unified_strdate, unified_timestamp as unified_timestamp
from .adobepass import AdobePassIE as AdobePassIE
from .common import InfoExtractor as InfoExtractor

class ESPNIE(InfoExtractor): ...

class ESPNArticleIE(InfoExtractor):
    @classmethod
    def suitable(cls, url): ...

class FiveThirtyEightIE(InfoExtractor): ...
class ESPNCricInfoIE(InfoExtractor): ...
class WatchESPNIE(AdobePassIE): ...
