from ..utils import ExtractorError as ExtractorError, OnDemandPagedList as OnDemandPagedList, clean_html as clean_html, determine_ext as determine_ext, format_field as format_field, int_or_none as int_or_none, join_nonempty as join_nonempty, parse_codecs as parse_codecs, parse_iso8601 as parse_iso8601, url_or_none as url_or_none, urljoin as urljoin
from ..utils.traversal import traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class FloatplaneBaseIE(InfoExtractor): ...
class FloatplaneIE(FloatplaneBaseIE): ...
class FloatplaneChannelIE(InfoExtractor): ...
