from ..utils import int_or_none as int_or_none, parse_duration as parse_duration, parse_iso8601 as parse_iso8601, str_or_none as str_or_none, str_to_int as str_to_int, try_get as try_get, unified_timestamp as unified_timestamp, url_or_none as url_or_none
from .common import InfoExtractor as InfoExtractor

class FourTubeBaseIE(InfoExtractor): ...

class FourTubeIE(FourTubeBaseIE):
    IE_NAME: str

class FuxIE(FourTubeBaseIE): ...
class PornTubeIE(FourTubeBaseIE): ...
class PornerBrosIE(FourTubeBaseIE): ...
