from ..utils import ExtractorError as ExtractorError, js_to_json as js_to_json, smuggle_url as smuggle_url, str_or_none as str_or_none, traverse_obj as traverse_obj, unescapeHTML as unescapeHTML
from .common import InfoExtractor as InfoExtractor

class GeniusIE(InfoExtractor): ...
class GeniusLyricsIE(InfoExtractor): ...
