from ..utils import clean_html as clean_html, join_nonempty as join_nonempty, parse_duration as parse_duration, str_or_none as str_or_none, traverse_obj as traverse_obj, unified_strdate as unified_strdate, unified_timestamp as unified_timestamp, urlhandle_detect_ext as urlhandle_detect_ext
from .common import InfoExtractor as InfoExtractor

class GlobalPlayerBaseIE(InfoExtractor): ...
class GlobalPlayerLiveIE(GlobalPlayerBaseIE): ...
class GlobalPlayerLivePlaylistIE(GlobalPlayerBaseIE): ...
class GlobalPlayerAudioIE(GlobalPlayerBaseIE): ...
class GlobalPlayerAudioEpisodeIE(GlobalPlayerBaseIE): ...
class GlobalPlayerVideoIE(GlobalPlayerBaseIE): ...
