from ..utils import traverse_obj as traverse_obj, urljoin as urljoin
from .common import InfoExtractor as InfoExtractor

class IslamChannelIE(InfoExtractor): ...
class IslamChannelSeriesIE(InfoExtractor): ...
