from ..utils import int_or_none as int_or_none, str_or_none as str_or_none, traverse_obj as traverse_obj, urljoin as urljoin
from .common import InfoExtractor as InfoExtractor

class ITProTVBaseIE(InfoExtractor): ...
class ITProTVIE(ITProTVBaseIE): ...
class ITProTVCourseIE(ITProTVBaseIE): ...
