from ..networking import HEADRequest as HEADRequest
from ..utils import clean_html as clean_html, int_or_none as int_or_none, try_get as try_get, urlhandle_detect_ext as urlhandle_detect_ext
from .common import InfoExtractor as InfoExtractor

class JamendoIE(InfoExtractor): ...
class JamendoAlbumIE(JamendoIE): ...
