from ..utils import int_or_none as int_or_none, parse_qs as parse_qs, traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class LastFMPlaylistBaseIE(InfoExtractor): ...
class LastFMPlaylistIE(LastFMPlaylistBaseIE): ...
class LastFMUserIE(LastFMPlaylistBaseIE): ...
class LastFMIE(InfoExtractor): ...
