from ..utils import InAdvancePagedList as InAdvancePagedList, traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class LeFigaroVideoEmbedIE(InfoExtractor): ...
class LeFigaroVideoSectionIE(InfoExtractor): ...
