from ..utils import ExtractorError as ExtractorError, GeoRestrictedError as GeoRestrictedError, OnDemandPagedList as OnDemandPagedList, int_or_none as int_or_none, try_get as try_get, update_url_query as update_url_query, urljoin as urljoin
from .theplatform import ThePlatformBaseIE as ThePlatformBaseIE

class MediasetIE(ThePlatformBaseIE): ...
class MediasetShowIE(MediasetIE): ...
