from ..utils import clean_html as clean_html, filter_dict as filter_dict, parse_qs as parse_qs, remove_end as remove_end, traverse_obj as traverse_obj, update_url_query as update_url_query, urljoin as urljoin
from .common import InfoExtractor as InfoExtractor

class MediaStreamBaseIE(InfoExtractor): ...
class MediaStreamIE(MediaStreamBaseIE): ...
class WinSportsVideoIE(MediaStreamBaseIE): ...
