from ..utils import int_or_none as int_or_none, parse_iso8601 as parse_iso8601, parse_resolution as parse_resolution, traverse_obj as traverse_obj, unified_timestamp as unified_timestamp, url_basename as url_basename, url_or_none as url_or_none
from .common import InfoExtractor as InfoExtractor

class MicrosoftEmbedIE(InfoExtractor): ...
class MicrosoftMediusBaseIE(InfoExtractor): ...
class MicrosoftMediusIE(MicrosoftMediusBaseIE): ...
class MicrosoftLearnPlaylistIE(InfoExtractor): ...
class MicrosoftLearnEpisodeIE(MicrosoftMediusBaseIE): ...
class MicrosoftLearnSessionIE(InfoExtractor): ...
class MicrosoftBuildIE(InfoExtractor): ...
