from ..utils import date_from_str as date_from_str, format_field as format_field, try_get as try_get, unified_strdate as unified_strdate
from .common import InfoExtractor as InfoExtractor

class MusicdexBaseIE(InfoExtractor): ...
class MusicdexSongIE(MusicdexBaseIE): ...
class MusicdexAlbumIE(MusicdexBaseIE): ...
class MusicdexPageIE(MusicdexBaseIE): ...
class MusicdexArtistIE(MusicdexPageIE): ...
class MusicdexPlaylistIE(MusicdexPageIE): ...
