from ..networking import HEADRequest as HEADRequest
from ..utils import get_element_by_class as get_element_by_class, int_or_none as int_or_none, try_call as try_call, url_or_none as url_or_none, urlhandle_detect_ext as urlhandle_detect_ext
from ..utils.traversal import traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class Mx3BaseIE(InfoExtractor): ...
class Mx3IE(Mx3BaseIE): ...
class Mx3NeoIE(Mx3BaseIE): ...
class Mx3VolksmusikIE(Mx3BaseIE): ...
