from ..networking import HEADRequest as HEADRequest
from ..utils import ExtractorError as ExtractorError, RegexNotFoundError as RegexNotFoundError, UserNotLive as UserNotLive, clean_html as clean_html, determine_ext as determine_ext, extract_attributes as extract_attributes, float_or_none as float_or_none, get_element_html_by_class as get_element_html_by_class, int_or_none as int_or_none, join_nonempty as join_nonempty, make_archive_id as make_archive_id, mimetype2ext as mimetype2ext, parse_age_limit as parse_age_limit, parse_duration as parse_duration, parse_iso8601 as parse_iso8601, remove_end as remove_end, try_get as try_get, unescapeHTML as unescapeHTML, unified_timestamp as unified_timestamp, update_url_query as update_url_query, url_basename as url_basename, url_or_none as url_or_none
from ..utils.traversal import require as require, traverse_obj as traverse_obj
from .adobepass import AdobePassIE as AdobePassIE
from .common import InfoExtractor as InfoExtractor
from .theplatform import ThePlatformBaseIE as ThePlatformBaseIE, ThePlatformIE as ThePlatformIE, default_ns as default_ns

class NBCUniversalBaseIE(ThePlatformBaseIE): ...
class NBCIE(NBCUniversalBaseIE): ...
class NBCSportsVPlayerIE(InfoExtractor): ...
class NBCSportsIE(InfoExtractor): ...
class NBCSportsStreamIE(AdobePassIE): ...
class NBCNewsIE(ThePlatformIE): ...

class NBCOlympicsIE(InfoExtractor):
    IE_NAME: str

class NBCOlympicsStreamIE(AdobePassIE):
    IE_NAME: str

class NBCStationsIE(InfoExtractor): ...
class BravoTVIE(NBCUniversalBaseIE): ...
class SyfyIE(NBCUniversalBaseIE): ...
