from ..networking.exceptions import HTTPError as HTTPError
from ..utils import ExtractorError as ExtractorError, determine_ext as determine_ext, int_or_none as int_or_none, parse_duration as parse_duration, parse_iso8601 as parse_iso8601, str_or_none as str_or_none, try_get as try_get, update_url_query as update_url_query, url_or_none as url_or_none, urljoin as urljoin
from .common import InfoExtractor as InfoExtractor

class NRKBaseIE(InfoExtractor): ...
class NRKIE(NRKBaseIE): ...

class NRKTVIE(InfoExtractor):
    IE_DESC: str

class NRKTVEpisodeIE(InfoExtractor): ...
class NRKTVSerieBaseIE(NRKBaseIE): ...

class NRKTVSeasonIE(NRKTVSerieBaseIE):
    @classmethod
    def suitable(cls, url): ...

class NRKTVSeriesIE(NRKTVSerieBaseIE):
    @classmethod
    def suitable(cls, url): ...

class NRKTVDirekteIE(NRKTVIE):
    IE_DESC: str

class NRKRadioPodkastIE(InfoExtractor): ...
class NRKPlaylistBaseIE(InfoExtractor): ...
class NRKPlaylistIE(NRKPlaylistBaseIE): ...
class NRKTVEpisodesIE(NRKPlaylistBaseIE): ...

class NRKSkoleIE(InfoExtractor):
    IE_DESC: str
