from ..utils import ExtractorError as ExtractorError, clean_html as clean_html, determine_ext as determine_ext, extract_attributes as extract_attributes, float_or_none as float_or_none, get_elements_html_by_class as get_elements_html_by_class, int_or_none as int_or_none, merge_dicts as merge_dicts, mimetype2ext as mimetype2ext, parse_iso8601 as parse_iso8601, remove_end as remove_end, remove_start as remove_start, str_or_none as str_or_none, traverse_obj as traverse_obj, url_or_none as url_or_none
from .common import InfoExtractor as InfoExtractor

class NYTimesBaseIE(InfoExtractor): ...
class NYTimesIE(NYTimesBaseIE): ...
class NYTimesArticleIE(NYTimesBaseIE): ...

class NYTimesCookingIE(NYTimesBaseIE):
    IE_NAME: str

class NYTimesCookingRecipeIE(InfoExtractor): ...
