from ..utils import traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor
from .zype import ZypeIE as ZypeIE

class OfTVIE(InfoExtractor): ...
class OfTVPlaylistIE(InfoExtractor): ...
