from ..utils import ExtractorError as ExtractorError, determine_ext as determine_ext, int_or_none as int_or_none, parse_iso8601 as parse_iso8601, traverse_obj as traverse_obj, variadic as variadic
from .common import InfoExtractor as InfoExtractor

class OpencastBaseIE(InfoExtractor): ...
class OpencastIE(OpencastBaseIE): ...
class OpencastPlaylistIE(OpencastBaseIE): ...
