from ..utils import ExtractorError as ExtractorError, Popen as Popen, check_executable as check_executable, format_field as format_field, get_exe_version as get_exe_version, is_outdated_version as is_outdated_version, shell_quote as shell_quote
from _typeshed import Incomplete

def cookie_to_dict(cookie): ...
def cookie_jar_to_list(cookie_jar): ...

class PhantomJSwrapper:
    INSTALL_HINT: str
    exe: Incomplete
    extractor: Incomplete
    options: Incomplete
    def __init__(self, extractor, required_version=None, timeout: int = 10000) -> None: ...
    def __del__(self) -> None: ...
    def get(self, url, html=None, video_id=None, note=None, note2: str = 'Executing JS on webpage', headers={}, jscode: str = 'saveAndExit();'): ...
    def execute(self, jscode, video_id=None, *, note: str = 'Executing JS'): ...
