from ..utils import determine_ext as determine_ext, float_or_none as float_or_none, int_or_none as int_or_none, str_or_none as str_or_none, strip_or_none as strip_or_none, traverse_obj as traverse_obj, unified_timestamp as unified_timestamp, url_or_none as url_or_none
from .common import InfoExtractor as InfoExtractor

class PinterestBaseIE(InfoExtractor): ...
class PinterestIE(PinterestBaseIE): ...

class PinterestCollectionIE(PinterestBaseIE):
    @classmethod
    def suitable(cls, url): ...
