from ..utils import ExtractorError as ExtractorError, try_get as try_get
from ..utils.traversal import traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class PokerGoBaseIE(InfoExtractor): ...
class PokerGoIE(PokerGoBaseIE): ...
class PokerGoCollectionIE(PokerGoBaseIE): ...
