from ..utils import int_or_none as int_or_none, join_nonempty as join_nonempty, js_to_json as js_to_json, parse_duration as parse_duration, strftime_or_none as strftime_or_none, traverse_obj as traverse_obj, unified_strdate as unified_strdate, urljoin as urljoin
from .common import InfoExtractor as InfoExtractor

class RadioFranceIE(InfoExtractor):
    IE_NAME: str

class RadioFranceBaseIE(InfoExtractor): ...
class FranceCultureIE(RadioFranceBaseIE): ...
class RadioFranceLiveIE(RadioFranceBaseIE): ...
class RadioFrancePlaylistBaseIE(RadioFranceBaseIE): ...
class RadioFrancePodcastIE(RadioFrancePlaylistBaseIE): ...
class RadioFranceProfileIE(RadioFrancePlaylistBaseIE): ...
class RadioFranceProgramScheduleIE(RadioFranceBaseIE): ...
