from ..utils import ExtractorError as ExtractorError, parse_qs as parse_qs, remove_start as remove_start, traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class RbgTumIE(InfoExtractor): ...
class RbgTumCourseIE(InfoExtractor): ...
class RbgTumNewCourseIE(InfoExtractor): ...
