from ..networking.exceptions import HTTPError as HTTPError
from ..utils import ExtractorError as ExtractorError, float_or_none as float_or_none
from .common import InfoExtractor as InfoExtractor

class RedBullTVIE(InfoExtractor):
    def extract_info(self, video_id): ...

class RedBullEmbedIE(RedBullTVIE): ...
class RedBullTVRrnContentIE(InfoExtractor): ...
class RedBullIE(InfoExtractor): ...
