from ..utils import int_or_none as int_or_none, parse_codecs as parse_codecs, parse_qs as parse_qs, try_get as try_get, urljoin as urljoin
from .common import InfoExtractor as InfoExtractor

class SeznamZpravyIE(InfoExtractor): ...
class SeznamZpravyArticleIE(InfoExtractor): ...
