from ..utils import make_archive_id as make_archive_id, try_get as try_get, unified_timestamp as unified_timestamp
from .bunnycdn import BunnyCdnIE as BunnyCdnIE
from .common import InfoExtractor as InfoExtractor
from _typeshed import Incomplete

class SovietsClosetBaseIE(InfoExtractor):
    MEDIADELIVERY_REFERER: Incomplete
    def parse_nuxt_jsonp(self, nuxt_jsonp_url, video_id, name): ...
    def video_meta(self, video_id, game_name, category_name, episode_number, stream_date): ...

class SovietsClosetIE(SovietsClosetBaseIE): ...
class SovietsClosetPlaylistIE(SovietsClosetBaseIE): ...
