from ..utils import OnDemandPagedList as OnDemandPagedList, format_field as format_field, int_or_none as int_or_none, smuggle_url as smuggle_url
from .common import InfoExtractor as InfoExtractor

class StoryFireBaseIE(InfoExtractor): ...
class StoryFireIE(StoryFireBaseIE): ...
class StoryFireUserIE(StoryFireBaseIE): ...
class StoryFireSeriesIE(StoryFireBaseIE): ...
