from ..utils import clean_html as clean_html, int_or_none as int_or_none, join_nonempty as join_nonempty, str_or_none as str_or_none, url_or_none as url_or_none
from ..utils.traversal import traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class TapTapBaseIE(InfoExtractor): ...
class TapTapMomentIE(TapTapBaseIE): ...
class TapTapAppIE(TapTapBaseIE): ...
class TapTapIntlBaseIE(TapTapBaseIE): ...
class TapTapAppIntlIE(TapTapIntlBaseIE): ...
class TapTapPostIntlIE(TapTapIntlBaseIE): ...
