from ..utils import ExtractorError as ExtractorError, clean_html as clean_html, determine_ext as determine_ext, make_archive_id as make_archive_id, merge_dicts as merge_dicts, mimetype2ext as mimetype2ext, parse_duration as parse_duration, parse_qs as parse_qs, traverse_obj as traverse_obj, unified_timestamp as unified_timestamp, url_or_none as url_or_none, urljoin as urljoin
from .turner import TurnerBaseIE as TurnerBaseIE

class TeamcocoBaseIE(TurnerBaseIE): ...
class TeamcocoIE(TeamcocoBaseIE): ...
class ConanClassicIE(TeamcocoBaseIE): ...
