from ..utils import OnDemandPagedList as OnDemandPagedList, determine_ext as determine_ext, parse_iso8601 as parse_iso8601, traverse_obj as traverse_obj
from .common import InfoExtractor as InfoExtractor

class TuneInBaseIE(InfoExtractor): ...
class TuneInStationIE(TuneInBaseIE): ...
class TuneInPodcastIE(TuneInBaseIE): ...
class TuneInPodcastEpisodeIE(TuneInBaseIE): ...

class TuneInShortenerIE(InfoExtractor):
    IE_NAME: str
    IE_DESC: bool
