from ..utils import extract_attributes as extract_attributes, get_element_html_by_class as get_element_html_by_class, remove_start as remove_start
from .common import InfoExtractor as InfoExtractor

class VTVGoIE(InfoExtractor): ...
class VTVIE(InfoExtractor): ...
