from ..utils import determine_ext as determine_ext, join_nonempty as join_nonempty, xpath_text as xpath_text
from .common import InfoExtractor as InfoExtractor

class WebcasterIE(InfoExtractor): ...
class WebcasterFeedIE(InfoExtractor): ...
