from ..utils import int_or_none as int_or_none, make_archive_id as make_archive_id, mimetype2ext as mimetype2ext, parse_resolution as parse_resolution, str_or_none as str_or_none, strip_jsonp as strip_jsonp, traverse_obj as traverse_obj, truncate_string as truncate_string, url_or_none as url_or_none, urlencode_postdata as urlencode_postdata, urljoin as urljoin
from .common import InfoExtractor as InfoExtractor

class WeiboBaseIE(InfoExtractor): ...
class WeiboIE(WeiboBaseIE): ...
class WeiboVideoIE(WeiboBaseIE): ...
class WeiboUserIE(WeiboBaseIE): ...
