from ..dependencies import Cryptodome as Cryptodome
from ..utils import ExtractorError as ExtractorError, int_or_none as int_or_none, jwt_decode_hs256 as jwt_decode_hs256, traverse_obj as traverse_obj, try_call as try_call, url_basename as url_basename, url_or_none as url_or_none, urlencode_postdata as urlencode_postdata, variadic as variadic
from .common import InfoExtractor as InfoExtractor

class WrestleUniverseBaseIE(InfoExtractor): ...
class WrestleUniverseVODIE(WrestleUniverseBaseIE): ...
class WrestleUniversePPVIE(WrestleUniverseBaseIE): ...
