from ..networking.exceptions import HTTPError as HTTPError
from ..utils import ExtractorError as ExtractorError, int_or_none as int_or_none, join_nonempty as join_nonempty, try_get as try_get, url_or_none as url_or_none, urlencode_postdata as urlencode_postdata
from .common import InfoExtractor as InfoExtractor

class ZattooPlatformBaseIE(InfoExtractor): ...
class ZattooBaseIE(ZattooPlatformBaseIE): ...
class ZattooIE(ZattooBaseIE): ...

class ZattooLiveIE(ZattooBaseIE):
    @classmethod
    def suitable(cls, url): ...

class ZattooMoviesIE(ZattooBaseIE): ...
class ZattooRecordingsIE(ZattooBaseIE): ...
class NetPlusTVBaseIE(ZattooPlatformBaseIE): ...
class NetPlusTVIE(NetPlusTVBaseIE): ...

class NetPlusTVLiveIE(NetPlusTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class NetPlusTVRecordingsIE(NetPlusTVBaseIE): ...
class MNetTVBaseIE(ZattooPlatformBaseIE): ...
class MNetTVIE(MNetTVBaseIE): ...

class MNetTVLiveIE(MNetTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class MNetTVRecordingsIE(MNetTVBaseIE): ...
class WalyTVBaseIE(ZattooPlatformBaseIE): ...
class WalyTVIE(WalyTVBaseIE): ...

class WalyTVLiveIE(WalyTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class WalyTVRecordingsIE(WalyTVBaseIE): ...
class BBVTVBaseIE(ZattooPlatformBaseIE): ...
class BBVTVIE(BBVTVBaseIE): ...

class BBVTVLiveIE(BBVTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class BBVTVRecordingsIE(BBVTVBaseIE): ...
class VTXTVBaseIE(ZattooPlatformBaseIE): ...
class VTXTVIE(VTXTVBaseIE): ...

class VTXTVLiveIE(VTXTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class VTXTVRecordingsIE(VTXTVBaseIE): ...
class GlattvisionTVBaseIE(ZattooPlatformBaseIE): ...
class GlattvisionTVIE(GlattvisionTVBaseIE): ...

class GlattvisionTVLiveIE(GlattvisionTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class GlattvisionTVRecordingsIE(GlattvisionTVBaseIE): ...
class SAKTVBaseIE(ZattooPlatformBaseIE): ...
class SAKTVIE(SAKTVBaseIE): ...

class SAKTVLiveIE(SAKTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class SAKTVRecordingsIE(SAKTVBaseIE): ...
class EWETVBaseIE(ZattooPlatformBaseIE): ...
class EWETVIE(EWETVBaseIE): ...

class EWETVLiveIE(EWETVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class EWETVRecordingsIE(EWETVBaseIE): ...
class QuantumTVBaseIE(ZattooPlatformBaseIE): ...
class QuantumTVIE(QuantumTVBaseIE): ...

class QuantumTVLiveIE(QuantumTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class QuantumTVRecordingsIE(QuantumTVBaseIE): ...
class OsnatelTVBaseIE(ZattooPlatformBaseIE): ...
class OsnatelTVIE(OsnatelTVBaseIE): ...

class OsnatelTVLiveIE(OsnatelTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class OsnatelTVRecordingsIE(OsnatelTVBaseIE): ...
class EinsUndEinsTVBaseIE(ZattooPlatformBaseIE): ...
class EinsUndEinsTVIE(EinsUndEinsTVBaseIE): ...

class EinsUndEinsTVLiveIE(EinsUndEinsTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class EinsUndEinsTVRecordingsIE(EinsUndEinsTVBaseIE): ...
class SaltTVBaseIE(ZattooPlatformBaseIE): ...
class SaltTVIE(SaltTVBaseIE): ...

class SaltTVLiveIE(SaltTVBaseIE):
    @classmethod
    def suitable(cls, url): ...

class SaltTVRecordingsIE(SaltTVBaseIE): ...
