import abc
from .common import RequestHandler as RequestHandler, Response as Response

class WebSocketResponse(Response):
    def send(self, message: bytes | str): ...
    def recv(self) -> None: ...

class WebSocketRequestHandler(RequestHandler, abc.ABC, metaclass=abc.ABCMeta): ...
