from .utils import expand_path as expand_path, traverse_obj as traverse_obj, version_tuple as version_tuple, write_json_file as write_json_file
from .version import __version__ as __version__

class Cache:
    def __init__(self, ydl) -> None: ...
    @property
    def enabled(self): ...
    def store(self, section, key, data, dtype: str = 'json') -> None: ...
    def load(self, section, key, dtype: str = 'json', default=None, *, min_ver=None): ...
    def remove(self) -> None: ...
